language: csharp
solution: AppVeyorDotnetSandbox.sln

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0
mono: latest

install:
  - dotnet restore

script:
  - dotnet build
  - ./Test.sh
