language: csharp
solution: AppVeyorDotnetSandbox.sln

matrix:
  include:
    - dotnet: 2.0.3
      os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
    - dotnet: 1.1.8
      os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest

install:
  - dotnet restore

script:
  - ./Test.sh
