language: csharp
solution: AppVeyorDotnetSandbox.sln

matrix:
  include:
    - dotnet: 2.0.0
      os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
    - dotnet: 1.1.7
      os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest

install:
  - dotnet restore

script:
#  - dotnet build -f netcoreapp1.1
#  - dotnet build -f netcoreapp2.0
  - ./Test.sh
