image: Visual Studio 2017

environment:
  matrix:
    - target_framework: netcoreapp2.1
      is_32bit: False
    #- target_framework: mono
    #  is_32bit: False
    #- target_framework: mono
    #  is_32bit: True
    #- target_framework: netcoreapp1.1
    #  is_32bit: False
    #- target_framework: netcoreapp1.1
    #  is_32bit: True
    #- target_framework: netcoreapp2.0
    #  is_32bit: False
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
    #- target_framework: netcoreapp2.0
    #  is_32bit: True
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #- target_framework: net462
    #  is_32bit: False
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #- target_framework: net462
    #  is_32bit: True

install:
  - ps: |
        if ($env:target_framework -eq "mono") { 
          if ($env:is_32bit -eq "True") { 
            cinst mono --x86
          } else { 
            cinst mono
          }
        }

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release -f $env:target_framework

test_script:
  - ps: .\Test.ps1 $env:target_framework $env:is_32bit

deploy: off
