image: Visual Studio 2015

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --packages packages

build_script:
  #- cmd: PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '.\AppVeyorDotnetSandbox\build.ps1'"
  - cmd: dotnet build -c Release

test_script:
  - cmd: .\AppVeyorDotnetSandbox\Test.cmd

deploy: off
