image: Visual Studio 2017

install:
  - cinst mono

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore

build_script:
  #- cmd: PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '.\AppVeyorDotnetSandbox\build.ps1'"
  - cmd: dotnet build -c Release

test_script:
  - ps: .\Test.ps1

deploy: off
