image: Visual Studio 2017

install:
  - cinst mono

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore

environment:
  matrix:
    - target_framework: netcoreapp1.1
      is_32bit: False
    - target_framework: netcoreapp1.1
      is_32bit: True
    - target_framework: netcoreapp2.0
      is_32bit: False
    - target_framework: netcoreapp2.0
      is_32bit: True
    - target_framework: net462
      is_32bit: False
    - target_framework: net462
      is_32bit: True

build_script:
  - cmd: dotnet build -c Release

test_script:
  - ps: .\Test.ps1 $(target_framework) $(is_32bit)

deploy: off
